//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 09:17:18 PM ALMT 
//


package soap.logistic.district;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.logistic.district package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.logistic.district
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateDistrictRequest }
     * 
     */
    public UpdateDistrictRequest createUpdateDistrictRequest() {
        return new UpdateDistrictRequest();
    }

    /**
     * Create an instance of {@link GetDistrictIdRequest }
     * 
     */
    public GetDistrictIdRequest createGetDistrictIdRequest() {
        return new GetDistrictIdRequest();
    }

    /**
     * Create an instance of {@link DeleteDistrictIdRequest }
     * 
     */
    public DeleteDistrictIdRequest createDeleteDistrictIdRequest() {
        return new DeleteDistrictIdRequest();
    }

    /**
     * Create an instance of {@link AddDistrictRequest }
     * 
     */
    public AddDistrictRequest createAddDistrictRequest() {
        return new AddDistrictRequest();
    }

    /**
     * Create an instance of {@link DeleteDistrictIdResponse }
     * 
     */
    public DeleteDistrictIdResponse createDeleteDistrictIdResponse() {
        return new DeleteDistrictIdResponse();
    }

    /**
     * Create an instance of {@link AddDistrictResponse }
     * 
     */
    public AddDistrictResponse createAddDistrictResponse() {
        return new AddDistrictResponse();
    }

    /**
     * Create an instance of {@link District }
     * 
     */
    public District createDistrict() {
        return new District();
    }

    /**
     * Create an instance of {@link UpdateDistrictResponse }
     * 
     */
    public UpdateDistrictResponse createUpdateDistrictResponse() {
        return new UpdateDistrictResponse();
    }

    /**
     * Create an instance of {@link GetDistrictIdResponse }
     * 
     */
    public GetDistrictIdResponse createGetDistrictIdResponse() {
        return new GetDistrictIdResponse();
    }

}
