//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.17 at 10:45:01 PM ALMT 
//


package soap.logistic.city;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.logistic.city package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.logistic.city
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteCityIdRequest }
     * 
     */
    public DeleteCityIdRequest createDeleteCityIdRequest() {
        return new DeleteCityIdRequest();
    }

    /**
     * Create an instance of {@link GetCityIdResponse }
     * 
     */
    public GetCityIdResponse createGetCityIdResponse() {
        return new GetCityIdResponse();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link UpdateCityRequest }
     * 
     */
    public UpdateCityRequest createUpdateCityRequest() {
        return new UpdateCityRequest();
    }

    /**
     * Create an instance of {@link GetCityIdRequest }
     * 
     */
    public GetCityIdRequest createGetCityIdRequest() {
        return new GetCityIdRequest();
    }

    /**
     * Create an instance of {@link DeleteCityIdResponse }
     * 
     */
    public DeleteCityIdResponse createDeleteCityIdResponse() {
        return new DeleteCityIdResponse();
    }

    /**
     * Create an instance of {@link AddCityResponse }
     * 
     */
    public AddCityResponse createAddCityResponse() {
        return new AddCityResponse();
    }

    /**
     * Create an instance of {@link UpdateCityResponse }
     * 
     */
    public UpdateCityResponse createUpdateCityResponse() {
        return new UpdateCityResponse();
    }

    /**
     * Create an instance of {@link AddCityRequest }
     * 
     */
    public AddCityRequest createAddCityRequest() {
        return new AddCityRequest();
    }

}
