//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.17 at 10:45:01 PM ALMT 
//


package soap.logistic.country;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.logistic.country package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.logistic.country
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteCountryIdRequest }
     * 
     */
    public DeleteCountryIdRequest createDeleteCountryIdRequest() {
        return new DeleteCountryIdRequest();
    }

    /**
     * Create an instance of {@link UpdateCountryResponse }
     * 
     */
    public UpdateCountryResponse createUpdateCountryResponse() {
        return new UpdateCountryResponse();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link GetCountryIdResponse }
     * 
     */
    public GetCountryIdResponse createGetCountryIdResponse() {
        return new GetCountryIdResponse();
    }

    /**
     * Create an instance of {@link DeleteCountryIdResponse }
     * 
     */
    public DeleteCountryIdResponse createDeleteCountryIdResponse() {
        return new DeleteCountryIdResponse();
    }

    /**
     * Create an instance of {@link AddCountryRequest }
     * 
     */
    public AddCountryRequest createAddCountryRequest() {
        return new AddCountryRequest();
    }

    /**
     * Create an instance of {@link UpdateCountryRequest }
     * 
     */
    public UpdateCountryRequest createUpdateCountryRequest() {
        return new UpdateCountryRequest();
    }

    /**
     * Create an instance of {@link GetCountryIdRequest }
     * 
     */
    public GetCountryIdRequest createGetCountryIdRequest() {
        return new GetCountryIdRequest();
    }

    /**
     * Create an instance of {@link AddCountryResponse }
     * 
     */
    public AddCountryResponse createAddCountryResponse() {
        return new AddCountryResponse();
    }

}
