//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.01 at 01:54:25 AM ALMT 
//


package soap.logistic.region;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.logistic.region package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.logistic.region
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteRegionIdRequest }
     * 
     */
    public DeleteRegionIdRequest createDeleteRegionIdRequest() {
        return new DeleteRegionIdRequest();
    }

    /**
     * Create an instance of {@link UpdateRegionRequest }
     * 
     */
    public UpdateRegionRequest createUpdateRegionRequest() {
        return new UpdateRegionRequest();
    }

    /**
     * Create an instance of {@link UpdateRegionResponse }
     * 
     */
    public UpdateRegionResponse createUpdateRegionResponse() {
        return new UpdateRegionResponse();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link GetRegionIdResponse }
     * 
     */
    public GetRegionIdResponse createGetRegionIdResponse() {
        return new GetRegionIdResponse();
    }

    /**
     * Create an instance of {@link AddRegionResponse }
     * 
     */
    public AddRegionResponse createAddRegionResponse() {
        return new AddRegionResponse();
    }

    /**
     * Create an instance of {@link AddRegionRequest }
     * 
     */
    public AddRegionRequest createAddRegionRequest() {
        return new AddRegionRequest();
    }

    /**
     * Create an instance of {@link DeleteRegionIdResponse }
     * 
     */
    public DeleteRegionIdResponse createDeleteRegionIdResponse() {
        return new DeleteRegionIdResponse();
    }

    /**
     * Create an instance of {@link GetRegionIdRequest }
     * 
     */
    public GetRegionIdRequest createGetRegionIdRequest() {
        return new GetRegionIdRequest();
    }

}
